export enum EVENT_ACITON_TYPE {
  ADD = "ADD_EVENT",
  SET = "SET_EVENTS",
  SET_CURRENT_EVENTS = "SET_CURRENT_EVENTS",
  SET_SELECTED_EVENT = "SET_SELECTED_EVENT",
  SET_CURRENT_EVENT = "SET_CURRENT_EVENT",
  TOGGLE_EVENT_MODAL = "TOGGLE_EVENT_MODAL",
}

export enum TAG_ACTION_TYPE {
  SET = "SET_TAGS",
  SET_SELECTED_TAGS = "SET_SELECTED_TAGS",
  SET_CURRENT_TAG = "SET_CURRENT_TAG",
  SET_DEFAULT_CURRENT_TAG = "SET_DEFAULT_CURRENT_TAG",
  TOGGLE_TAG_MODAL = "TOGGLE_TAG_MODAL",
}