export enum EVENT_ACITON_TYPE {
  ADD = "ADD_EVENT",
  SET = "SET_EVENTS",
  SET_CURRENT_EVENTS = "SET_CURRENT_EVENTS",
  SET_SELECTED_EVENT = "SET_SELECTED_EVENT"
}

export enum TAG_ACTION_TYPE {
  SET = "SET_TAGS",
  SET_SELECTED_TAGS = "SET_SELECTED_TAGS",
  SET_CURRENT_TAG = "SET_CURRENT_TAG",
  SET_DEFAULT_CURRENT_TAG = "SET_DEFAULT_CURRENT_TAG",
  TOGGLE_MODAL = "TOGGLE_MODAL",
}